# Generated by Django 5.1.4 on 2025-01-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0004_laudo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
