# Generated by Django 5.1.4 on 2025-01-30 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0005_delete_yourmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='laudotemplate',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_template_name_per_user'),
        ),
    ]
