# Generated by Django 5.1.4 on 2025-01-30 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0006_laudotemplate_unique_template_name_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='laudotemplate',
            name='unique_template_name_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='laudotemplate',
            unique_together={('name', 'user')},
        ),
    ]
